title: Edwin Suyitno # your name (or website title) here
logo: "/images/profile_picture.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Enthusiastic about data analysis, visualisation, mathematics/statistics, and everything in between.
  <br><br>
  Master in Mathematical and Statistical Modelling, University of Technology Sydney.
  <br><br>
  <a href="https://www.linkedin.com/in/edwin-suyitno/">LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
