CREATE TABLE pollinators (
    gbifID bigserial PRIMARY KEY,
    datasetKey UUID,
    occurrenceID TEXT,
    kingdom TEXT,
    phylum TEXT,
    class TEXT,
    order_name TEXT,
    family TEXT,
    genus TEXT,
    species TEXT,
    infraspecificEpithet TEXT,
    taxonRank TEXT,
    scientificName TEXT,
    verbatimScientificName TEXT,
    verbatimScientificNameAuthorship TEXT,
    countryCode TEXT,
    locality TEXT,
    stateProvince TEXT,
    occurrenceStatus TEXT,
    individualCount INT,
    publishingOrgKey UUID,
    decimalLatitude DOUBLE PRECISION,
    decimalLongitude DOUBLE PRECISION,
    coordinateUncertaintyInMeters DOUBLE PRECISION,
    coordinatePrecision DOUBLE PRECISION,
    elevation DOUBLE PRECISION,
    elevationAccuracy DOUBLE PRECISION,
    depth DOUBLE PRECISION,
    depthAccuracy DOUBLE PRECISION,
    eventDate TIMESTAMPTZ,
    day INT,
    month INT,
    year INT,
    taxonKey INT,
    speciesKey INT,
    basisOfRecord TEXT,
    institutionCode TEXT,
    collectionCode TEXT,
    catalogNumber TEXT,
    recordNumber TEXT,
    identifiedBy TEXT,
    dateIdentified TIMESTAMPTZ,
    license TEXT,
    rightsHolder TEXT,
    recordedBy TEXT,
    typeStatus TEXT,
    establishmentMeans TEXT,
    lastInterpreted TIMESTAMPTZ,
    mediaType TEXT,
    issue TEXT
);

COPY pollinators from '/home/rotisayabundar/Downloads/shuuheialb.github.io/projects/non-western-pollinator/occurences.csv'
	with (FORMAT CSV, DELIMITER E'\t', HEADER TRUE);